name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Add GitHub registry NuGet source
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/dotnet-websharper/index.json \
            --name github \
            --username intellifactory-gh \
            --password "${{ secrets.PAT_PACKAGE }}" \
            --store-password-in-clear-text

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: WebSharper.CredentialManagement.Sample

      - name: Build WebSharper Project
        run: dotnet build 
        working-directory: WebSharper.CredentialManagement.Sample

      - name: Install Vite
        run: npm install -g vite

      - name: Build Static Files with Vite
        run: npx vite build --outDir ../dist --base ./
        working-directory: WebSharper.CredentialManagement.Sample/wwwroot

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
