name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Add GitHub registry NuGet source
        shell: cmd
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/dotnet-websharper/index.json ^
          --name github ^
          --username intellifactory-gh ^
          --password "${{ secrets.PAT_PACKAGE }}" ^
          --store-password-in-clear-text

      - name: Build WebSharper Project
        run: dotnet build WebSharper.CredentialManagement.Sample/WebSharper.CredentialManagement.Sample.fsproj --configuration Release

      - name: Prepare Deployment
        run: |
          mkdir -p dist
          cp -r WebSharper.CredentialManagement.Sample/wwwroot/* dist/

      - name: Manual Deployment to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r dist/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
