name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet Packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Add GitHub registry NuGet source
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/dotnet-websharper/index.json \
          --name github \
          --username intellifactory-gh \
          --password "${{ secrets.PAT_PACKAGE }}" \
          --store-password-in-clear-text

      - name: Restore NuGet Packages
        run: dotnet restore WebSharper.CredentialManagement.Sample/WebSharper.CredentialManagement.Sample.fsproj

      - name: Build Binding Project
        run: dotnet build WebSharper.CredentialManagement/WebSharper.CredentialManagement.fsproj --configuration Release --no-restore -maxcpucount:1

      - name: Build Sample Project
        run: dotnet build WebSharper.CredentialManagement.Sample/WebSharper.CredentialManagement.Sample.fsproj --configuration Release --no-restore -maxcpucount:1

      - name: Prepare Deployment
        run: |
          mkdir -p dist
          cp -r WebSharper.CredentialManagement.Sample/wwwroot/* dist/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
